export const CODE_BANK:any  = {
  tcb: "Ngân hàng TMCP Kỹ thương Việt Nam (Techcombank)",
  coopbank: "Ngân hàng Hợp tác xã Việt Nam (COOPBANK)",
  acb: "Ngân hàng TMCP Á Châu (ACB)",
  kbhn: "Ngân hàng Kookmin - Chi nhánh Hà Nội",
  ibk: "Ngân hàng Công nghiệp Hàn Quốc (IBK)",
  vab: "Ngân hàng TMCP Việt Á (VietABank)",
  msb: "Ngân hàng TMCP Hàng Hải (MSB)",
  abb: "Ngân hàng TMCP An Bình (ABBANK)",
  liobank: "Ngân hàng số LioBank",
  vpb: "Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)",
  cbb: "Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam (CBBank)",
  kpb: "Ngân hàng Đại chúng Kasikornbank - Chi nhánh TP. Hồ Chí Minh (KBank)",
  wrb: "Ngân hàng TNHH MTV Woori Việt Nam (Woori)",
  hsbc: "Ngân hàng TNHH MTV HSBC (Việt Nam)",
  bnphcm: "Ngân hàng BNP Paribas - Chi nhánh TP. Hồ Chí Minh",
  gpb: "Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu (GPBank)",
  pbvn: "Ngân hàng TNHH MTV Public Việt Nam (PublicBank)",
  cake: "Ngân hàng số CAKE by VPBank",
  vtb: "Ngân hàng TMCP Công thương Việt Nam (VietinBank)",
  bvb: "Ngân hàng TMCP Bảo Việt (BaoVietBank)",
  hongleong: "Ngân hàng TNHH MTV Hongleong Việt Nam",
  kebhcm: "Ngân hàng KEB Hana - Chi nhánh TP. Hồ Chí Minh",
  bnphn: "Ngân hàng BNP Paribas - Chi nhánh Hà Nội",
  vib: "Ngân hàng TMCP Quốc tế Việt Nam (VIB)",
  vrb: "Ngân hàng Liên doanh Việt - Nga (VRB)",
  ocb: "Ngân hàng TMCP Phương Đông (OCB)",
  bab: "Ngân hàng TMCP Bắc Á (Bac A Bank)",
  kbhcm: "Ngân hàng Kookmin - Chi nhánh TP. Hồ Chí Minh",
  dab: "Ngân hàng TMCP Đông Á (Dong A Bank)",
  citibank: "Ngân hàng Citibank - Chi nhánh Hà Nội",
  ncb: "Ngân hàng TMCP Quốc Dân (NCB)",
  vcab: "Ngân hàng TMCP Bản Việt (Viet Capital Bank)",
  dbs: "DBS Bank Ltd - Chi nhánh TP. Hồ Chí Minh",
  nhb: "Ngân hàng Nonghyup - Chi nhánh Hà Nội",
  vtlmoney: "ViettelMoney",
  lpb: "Ngân hàng TMCP Lộc Phát Việt Nam (LPBank)",
  stb: "Ngân hàng TMCP Sài Gòn Thương Tín (Sacombank)",
  ubank: "Ngân hàng số Ubank by VPBank",
  shinhan: "Ngân hàng TNHH MTV Shinhan Việt Nam",
  sbc: "Ngân hàng TMCP Sài Gòn Công Thương (SaigonBank)",
  agr: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam (Agribank)",
  hdb: "Ngân hàng TMCP Phát triển TP. Hồ Chí Minh (HDBank)",
  pgb: "Ngân hàng TMCP Xăng dầu Petrolimex (PGBank)",
  mb: "Ngân hàng TMCP Quân đội (MBBank)",
  bidc: "Ngân hàng Đầu tư và Phát triển Campuchia – Chi nhánh Hà Nội",
  sab: "Ngân hàng TMCP Đông Nam Á (SeABank)",
  vnptmoney: "VNPTMoney",
  shb: "Ngân hàng TMCP Sài Gòn - Hà Nội (SHB)",
  nab: "Ngân hàng TMCP Nam Á (Nam A Bank)",
  cubhcm: "Ngân hàng Cathay United Bank – Chi nhánh TP. Hồ Chí Minh",
  pvcb: "Ngân hàng TMCP Đại Chúng Việt Nam (PVcomBank)",
  vbc: "Ngân hàng TMCP Việt Nam Thương Tín (VietBank)",
  uob: "Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh",
  tpb: "Ngân hàng TMCP Tiên Phong (TPBank)",
  umee: "Ngân hàng số Umee – Kiên Long Bank",
  cimb: "Ngân hàng TNHH MTV CIMB Việt Nam",
  klb: "Ngân hàng TMCP Kiên Long (KienLongBank)",
  vcb: "Ngân hàng TMCP Ngoại Thương Việt Nam (Vietcombank)",
  timo: "Ngân hàng số Timo by BVBank",
  ivb: "Ngân hàng TNHH Indovina (Indovina Bank)",
  scb: "Ngân hàng TMCP Sài Gòn (SCB)",
  bidv: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)",
  eib: "Ngân hàng TMCP Xuất Nhập khẩu Việt Nam (Eximbank)",
  scvn: "Ngân hàng TNHH MTV Standard Chartered Việt Nam",
  mbv: "Ngân hàng Thương mại TNHH MTV Đại Dương (OceanBank)",
  kebhn: "Ngân hàng KEB Hana - Chi nhánh Hà Nội"
};