export const draftDataSide = {
  errors: [],
  messages: [],
  success: true,
  result: [
    {
      id: 1,
      code: "HLS",
      name: "Sun World Hạ Long",
      address: "Bãi Cháy, TP Hạ Long, Quảng Ninh",
      description: "Hạ Long Park là công viên nước hiện đại hàng đầu của Đông Nam Á",
    },
    {
      id: 2,
      code: "BNC",
      name: "Sun World Bà Nà Hills",
      address: "Thôn An Sơn, Hòa Vang, Đà Nẵng",
      description:
        "Sun World Bà Nà Hills là một tổ hợp du lịch – giải trí – nghỉ dưỡng nằm ngay trong trung tâm thành phố Đà Nẵng.",
    },
    {
      id: 3,
      code: "HTI",
      name: "Hon thom",
      address: "Phú Quốc, Kiên Giang",
      description:
        'Hon Thom is likened to the pearl of An Thoi archipelago - south of Phu Quocisland (Kien Giang). Hon Thom Island is 5.7 km2 wide, with wild and romantic beauty."',
    },
    {
      id: 6,
      code: "FSS",
      name: "Sun World Fansipan Legend",
      address: "Thị xã Sa Pa, Lào Cai",
      description:
        "Sun World Fansipan Legend là một khu du lịch nằm tại đỉnh núi Fansipan, cao nhất Việt Nam với độ cao 3.143 mét, thuộc thị xã Sapa, tỉnh Lào Cai và cách thị xã Sapa khoảng 7km về phía Tây Nam.",
    },
  ],
  paginationData: {
    current: 1,
    numItemsPerPage: 20,
    currentItemCount: 4,
    pageCount: 1,
    totalCount: 4,
  },
};

export const draftDataProduct = {
  errors: [],
  messages: [],
  success: true,
  result: [
    {
      id: 10001400,
      code: "9304F7B7-ABBF-4736-4583-0195373FE764",
      name: "NL-VÉ CB CÁP&BUFFET TRƯA 4SEASONS SWH",
      description: null,
      unitPrice: 1150000,
      publicPrice: 1300000,
      personType: "ADULT",
      productType: "S2",
      category: null,
      openTime: "09:00:00",
      closeTime: "22:00:00",
      showTime: "08:00",
      restaurantCode: null,
      restaurantName: null,
      site: {
        code: "BNC",
        name: "Bà Nà Hills",
      },
      event: null,
      performances: [
        {
          id: 56630,
          performanceId: "56630",
          status: "Active",
          startDate: "2026-02-26",
          startTime: "",
          endDate: "2026-02-27",
          endTime: "",
        },
      ],
      ticketValidity: null,
      pricePolicy: {
        unitPrice: 1150000,

        publicPrice: 1300000,
        usageDate: "2026-02-26",
        validDateFrom: "2026-01-30",
        validDateTo: "2026-12-31",
      },
      multiple: 1,
      minQuantity: 1,
      priceRewardWallet: [],
    },
    {
      id: 10001675,
      code: "368B622D-56F2-F068-2987-019BBB51CB46",
      name: "COMBO ĐÊM NHÀ HÀNG 1901 NGƯỜI LỚN",
      description: null,
      unitPrice: 930000,
      publicPrice: 1000000,
      personType: "ADULT",
      productType: "S2",
      category: null,
      openTime: "00:00",
      closeTime: "17:30",
      showTime: "16:00",
      restaurantCode: "S1",
      restaurantName: "Nhà hàng Bốn Mùa",
      site: {
        code: "BNC",
        name: "Bà Nà Hills",
      },
      event: null,
      performances: [
        {
          id: 56630,
          performanceId: "56630",
          status: "Active",
          startDate: "2026-02-26",
          startTime: "",
          endDate: "2026-02-27",
          endTime: "",
        },
      ],
      ticketValidity: null,
      pricePolicy: {
        unitPrice: 930000,
        publicPrice: 1000000,
        usageDate: "2026-02-26",
        validDateFrom: "2026-01-16",
        validDateTo: "2026-12-31",
      },
      multiple: 1,
      minQuantity: 1,
      priceRewardWallet: [],
    },
    {
      id: 10002247,
      code: "9482E909-97A0-651B-6E86-019536D91DEE",
      name: "NGƯỜI LỚN _CB CÁP & BUFFET BỐN MÙA",
      description: null,
      unitPrice: 500000,

      publicPrice: 550000,
      personType: "CHILD",
      productType: "S2",
      category: null,
      openTime: "00:00",
      closeTime: "11:00",
      showTime: "10:30-12:30",
      restaurantCode: "S1",
      restaurantName: "Nhà hàng Bốn Mùa",
      site: {
        code: "BNC",
        name: "Bà Nà Hills",
      },
      event: null,
      performances: [
        {
          id: 56630,
          performanceId: "56630",
          status: "Active",
          startDate: "2026-02-26",
          startTime: "",
          endDate: "2026-02-27",
          endTime: "",
        },
      ],
      ticketValidity: null,
      pricePolicy: {
        unitPrice: 500000,
        publicPrice: 550000,
        usageDate: "2026-02-26",
        validDateFrom: "2026-01-30",
        validDateTo: "2026-12-31",
      },
      multiple: 1,
      minQuantity: 1,
      priceRewardWallet: [],
    },
  ],
  paginationData: {
    current: 1,
    numItemsPerPage: 50,
    currentItemCount: 3,
    pageCount: 1,
    totalCount: 3,
  },
};

export const draftDataTicket = {
  errors: [],
  messages: ["Creating sales order and generating ticket are success"],
  success: true,
  result: {
    orderCode: "0010092353",
    orderStatus: "success",
    orderDate: "2025-10-16 14:24:44",
    totalOrderPrice: 800000,
    items: [
      {
        productName: "Vé Cáp Chùa sau 17h_Trẻ em",
        productCode: "84A376FD-1905-FD77-74EC-0193056D6525",
        quantity: 1,
        siteCode: "SBD",
        totalPrice: 800000,
        unitPrice: 800000,
        usageDate: "2025-10-16",
        usageTime: null,
        productGroup: "30999002",
        isFaceIdRequired: "0",
        freeGoods: "0",
        tickets: [
          {
            ticketNumber: "KGNLKV7B3G2CP8",
            validDateFrom: "2025-10-16 00:00",
            validDateTo: "2025-10-20 00:00",
            status: "Active",
            noSequence: "",
            verifyCode: "",
            passengerName: null,
          },
        ],
      },
      {
        productName: "Vé Cáp Đỉnh Vân Sơn HDV",
        productCode: "BEB14636-EE63-A63B-2158-0197BFA16CF6",
        quantity: 1,
        siteCode: "SBD",
        totalPrice: 0,
        unitPrice: 0,
        usageDate: "2025-10-16",
        usageTime: null,
        productGroup: "30999005",

        isFaceIdRequired: "2",
        freeGoods: "1",
        tickets: [
          {
            ticketNumber: "",
            validDateFrom: "2025-10-16 00:00",
            validDateTo: "2025-10-20 23:59",
            status: "Active",
            noSequence: "",
            verifyCode: "7D66F0251BCD8D958E37",
            passengerName: null,
          },
        ],
      },
    ],
    pnr: "ALGVVYOSMJ",
    siteCode: null,
    totalItem: 2,
    totalTicket: 2,
    thirdPartyNumber: "TEST1_SBD_20251016_0002",
    referenceCode: "KKD050000001685",
  },
};
